version: '3'

services:
  nest:
    build: ./nest
    ports:
      - 3000:3000
      - 5555:5555
    volumes:
      - ./nest:/home/node/app
    environment:
      - NODE_ENV=development

  next:
    build: ./next
    ports:
      - 3001:3000
    volumes:
      - ./next:/home/node/app
    environment:
      - NODE_ENV=development
    
  db:
    image: mysql:latest
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: nest
  
volumes:
  mysql_data:
    driver: local